import os
import sys

env=DefaultEnvironment().Clone()
BIN_DIR=os.environ['BIN_DIR'];

env.Program(os.path.join(BIN_DIR, 'demo_share'), ['share.c', 'assets.c'])
env.Program(os.path.join(BIN_DIR, 'demo_qrcode'), ['qrcode.c', 'assets.c'])
env.Program(os.path.join(BIN_DIR, 'demo_lpr'), ['lpr.c', 'assets.c'])
env.Program(os.path.join(BIN_DIR, 'demo_battery'), ['battery.c', 'assets.c'])
env.Program(os.path.join(BIN_DIR, 'demo_image_picker'), ['image_picker.c', 'assets.c'])
env.Program(os.path.join(BIN_DIR, 'demo_wifi'), ['wifi.c', 'assets.c'])
env.Program(os.path.join(BIN_DIR, 'demo_foobar'), ['foobar.c', 'assets.c'])
env.Program(os.path.join(BIN_DIR, 'demo_ble'), Glob('ble*.c')+['assets.c'])
env.Program(os.path.join(BIN_DIR, 'demo_url_view'), ['url_view.c', 'assets.c'])
env.Program(os.path.join(BIN_DIR, 'demo_awake'), ['awake.c', 'assets.c'])
env.Program(os.path.join(BIN_DIR, 'demo_wake_lock'), ['wake_lock.c', 'assets.c'])
