import os
import sys

env=DefaultEnvironment().Clone()
BIN_DIR=os.environ['BIN_DIR'];

env.Program(os.path.join(BIN_DIR, 'demo_share'), ['share.c', 'assets.c'])
env.Program(os.path.join(BIN_DIR, 'demo_qrcode'), ['qrcode.c', 'assets.c'])
env.Program(os.path.join(BIN_DIR, 'demo_image_picker'), ['image_picker.c', 'assets.c'])

