import os
import sys

env=DefaultEnvironment().Clone()
LIB_DIR=os.environ['LIB_DIR'];

SOURCES = Glob('common/*.c') + Glob('share/*.c') \
  + Glob('lpr/*.c') \
  + Glob('qrcode/*.c') \
  + Glob('image_picker/*.c') \
  + Glob('wifi/*.c') \
  + Glob('ble/*.c') \
  + Glob('foobar/*.c') \
  + Glob('url_view/*.c') \
  + Glob('battery/*.c') \
  + Glob('misc/*.c') \
  + Glob('wake_lock/*.c') \
  + Glob('awake/*.c')
env.Library(os.path.join(LIB_DIR, 'plugins'), SOURCES);

